// Game Engine
class Game {
  constructor() { this.state="title"; this.world=null; this.player=null; this.renderer=null; this.crafting=new CraftingSystem(); this.mode="move"; this.running=false; }
  init(canvas) { this.renderer=new Renderer(canvas); this.newGame(); }
  newGame() { this.world=new World(WORLD_CONFIG.width,WORLD_CONFIG.height); let sx=Math.floor(WORLD_CONFIG.width/2); let sy=this.world.getSurface(sx)-2; this.player=new Player(sx,sy); inventory=new Inventory(9); inventory.addItem("WOOD",5); inventory.addItem("DIRT",10); this.state="play"; this.running=true; }
  update() { if(this.state!=="play"||!this.running)return; this.player.update(this.world); this.renderer.updateCam(this.player.x,this.player.y); }
  render() { this.renderer.clear(); if(this.state==="title"){this.renderer.drawTitle();return;} if(this.state==="play"){this.renderer.drawWorld(this.world);this.renderer.drawPlayer(this.player);this.renderer.drawCursor(this.player);this.renderer.drawHUD(this.player,inventory);} if(this.state==="crafting"){this.crafting.render(this.renderer.ctx,this.renderer.W,this.renderer.H);} }
  loop() { this.update(); this.render(); requestAnimationFrame(()=>this.loop()); }
  start() { this.loop(); }
  onScroll(dir) { if(this.state==="title"){this.newGame();return;} if(this.state==="crafting"){this.crafting.move(dir==="up"?"up":"down");return;} if(this.state==="play"){if(this.mode==="move"){if(dir==="up")this.player.jump();else inventory.scrollSelect(dir==="down"?1:-1);}else if(this.mode==="build"){this.player.moveCursor(dir==="up"?"up":"down");}} }
  onSide() { if(this.state==="title")return; if(this.state==="crafting"){if(this.crafting.browseMode){let av=this.crafting.getAvailable();if(av.length>0)this.crafting.quickCraft(this.crafting.browseIdx);}else if(this.crafting.result){this.crafting.craft();}else{let sel=inventory.getSelected();if(sel)this.crafting.placeItem(sel.id);} return;} if(this.state==="play"){if(this.mode==="move"){this.mode="build";}else{let cx=this.player.cursorX,cy=this.player.cursorY; let b=this.world.getBlock(cx,cy); if(b!=="AIR"){if(b==="CRAFTING_TABLE"){this.state="crafting";this.crafting.open();return;} let drop=this.world.breakBlock(cx,cy);if(drop)inventory.addItem(drop,1);}else{let sel=inventory.getSelected();if(sel&&ITEMS[sel.id]&&ITEMS[sel.id].placeable){this.world.setBlock(cx,cy,ITEMS[sel.id].blockType);inventory.removeItem(sel.id,1);}}}} }
  onLongPress() { if(this.state==="crafting"){this.crafting.browseMode=!this.crafting.browseMode;this.crafting.browseIdx=0;return;} if(this.state==="play"&&this.mode==="build"){this.mode="move";} }
  onBack() { if(this.state==="crafting"){this.crafting.close();this.state="play";return;} if(this.mode==="build")this.mode="move"; }
  handleKey(key) { if(key==="ArrowLeft"){this.player.moveLeft();} if(key==="ArrowRight"){this.player.moveRight();} if(key==="ArrowUp"){this.onScroll("up");} if(key==="ArrowDown"){this.onScroll("down");} if(key===" "){this.onSide();} if(key==="e"){this.onLongPress();} if(key==="Escape"){this.onBack();} }
}
