// Renderer - 240x282 R1 screen
class Renderer {
  constructor(canvas) { this.canvas=canvas; this.ctx=canvas.getContext("2d"); this.W=240; this.H=282; this.tileSize=12; this.camX=0; this.camY=0; }
  clear() { this.ctx.fillStyle="#87CEEB"; this.ctx.fillRect(0,0,this.W,this.H); }
  updateCam(px,py) { this.camX=px-this.W/this.tileSize/2; this.camY=py-this.H/this.tileSize/2; }
  drawWorld(world) { let ts=this.tileSize,ctx=this.ctx; let sx=Math.floor(this.camX),sy=Math.floor(this.camY); let cols=Math.ceil(this.W/ts)+2,rows=Math.ceil(this.H/ts)+2; for(let dx=0;dx<cols;dx++){for(let dy=0;dy<rows;dy++){let wx=sx+dx,wy=sy+dy; let b=world.getBlock(wx,wy); if(b==="AIR")continue; let block=BLOCKS[b]; if(!block||!block.color)continue; let px=(wx-this.camX)*ts,py=(wy-this.camY)*ts; ctx.fillStyle=block.color; ctx.fillRect(px,py,ts-1,ts-1);}} }
  drawPlayer(player) { let ts=this.tileSize,ctx=this.ctx; let px=(player.x-this.camX)*ts-ts*player.w/2,py=(player.y-player.h-this.camY)*ts; ctx.fillStyle="#4488ff"; ctx.fillRect(px,py,ts*player.w,ts*player.h); ctx.fillStyle="#ffcc88"; ctx.fillRect(px+2,py+1,ts*player.w-4,ts*0.4); }
  drawCursor(player) { let ts=this.tileSize,ctx=this.ctx; let px=(player.cursorX-this.camX)*ts,py=(player.cursorY-this.camY)*ts; ctx.strokeStyle="#fff"; ctx.lineWidth=1; ctx.strokeRect(px,py,ts-1,ts-1); }
  drawHUD(player,inv) { let ctx=this.ctx; ctx.fillStyle="rgba(0,0,0,0.5)"; ctx.fillRect(0,0,this.W,16); ctx.fillStyle="#f44"; ctx.font="10px monospace"; ctx.fillText("HP:"+player.hp+"/"+player.maxHp,4,12); let sel=inv.getSelected(); if(sel){let item=ITEMS[sel.id]; if(item)ctx.fillText(item.name+"x"+sel.count,90,12);} ctx.fillStyle="rgba(0,0,0,0.6)"; ctx.fillRect(0,this.H-24,this.W,24); let bw=24,pad=2,sx=(this.W-inv.slots.length*(bw+pad))/2; for(let i=0;i<inv.slots.length;i++){let x=sx+i*(bw+pad),y=this.H-23; ctx.fillStyle=i===inv.selected?"#ffcc00":"#555"; ctx.fillRect(x,y,bw,20); ctx.fillStyle="#333"; ctx.fillRect(x+1,y+1,bw-2,18); if(inv.slots[i]){let item=ITEMS[inv.slots[i].id]; if(item){ctx.fillStyle=item.color; ctx.font="12px monospace"; ctx.fillText(item.symbol,x+7,y+14); ctx.font="7px monospace"; ctx.fillStyle="#fff"; ctx.fillText(inv.slots[i].count,x+bw-10,y+18);}}} }
  drawTitle() { let ctx=this.ctx; ctx.fillStyle="#1a0a2e"; ctx.fillRect(0,0,this.W,this.H); ctx.fillStyle="#8844ff"; ctx.font="bold 18px monospace"; ctx.fillText("GHOST",75,80); ctx.fillText("BUILDER",60,105); ctx.fillStyle="#aaa"; ctx.font="10px monospace"; ctx.fillText("Created by",70,150); ctx.fillText("Jeff Hollaway",55,165); ctx.fillText("[GhostLegacyX]",50,180); ctx.fillStyle="#888"; ctx.font="9px monospace"; ctx.fillText("Scroll=Start",75,240); }
}
